### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by jorge-h2020** [ELELAB/CAncer-bioMarker-Prediction-Pipeline-CAMPP#1]
I'm trying to run CAMPP.R "sudo Rscript CAMPP.R" and I get several dependency errors.

I haven't  knowledge of the R language, I work on a linux platform.

cat /etc/issue
Ubuntu 18.04.2 LTS 

R --version
R version 3.4.4 (2018-03-15)  instalada por defecto mediante apt

sudo Rscript CAMPP.R &> >(grep -i error)
ERROR: dependency ‘locfit’ is not available for package ‘edgeR’
ERROR: dependency ‘car’ is not available for package ‘rstatix’
ERROR: dependency ‘mvtnorm’ is not available for package ‘maxstat’
ERROR: dependency ‘mvtnorm’ is not available for package ‘flexsurv’
ERROR: dependencies ‘cowplot’, ‘rstatix’ are not available for package ‘ggpubr’
ERROR: dependencies ‘ggpubr’, ‘maxstat’ are not available for package ‘survminer’
ERROR: dependency ‘car’ is not available for package ‘rstatix’
ERROR: dependency ‘mvtnorm’ is not available for package ‘maxstat’
ERROR: dependencies ‘cowplot’, ‘rstatix’ are not available for package ‘ggpubr’
ERROR: dependencies ‘ggpubr’, ‘maxstat’ are not available for package ‘survminer’
ERROR: dependency ‘latticeExtra’ is not available for package ‘Hmisc’
ERROR: dependency ‘Hmisc’ is not available for package ‘WGCNA’
ERROR: dependency ‘latticeExtra’ is not available for package ‘Hmisc’
ERROR: dependency ‘Hmisc’ is not available for package ‘WGCNA’
Error in FUN(X[[i]], ...) : there is no package called ‘edgeR’
Error: Ups! Something went wrong, one or more R-package dependencies are not installed correctly. Check the script CAMPPmissingpackages.R. Alternatively you can download and use the Packrat library freeze, see manual for specifics. Packrat library in brief:

Can CAMPP.R work on linux?

**Comment by ThildeBT** [comment]
Hi @jorge-h2020 
Yes, CAMPP.R should work just fine on linux. You shouldn't have to write sudo in front of rscript, I am here assuming that you are running it on your local machine. But either way this is not the problem. You need R version at least 3.6 to run, you currently have 3.4.4. Also, it would help me a lot if you could send me the command line so I know if you are using the renv library or installing the most updated version of the packages.
Best Thilde

**Comment by jorge-h2020** [comment]
hi @ThildeBT 

I use sudo to be able to install the R packages in /usr/local/lib/R/site-library.

To install R I use the ubuntu package manager (apt), in the Ubuntu 18.04 officials repositories. Currently it is version 3.4.4.

I just installed version 4 of R and following this tutorial
https://www.digitalocean.com/community/tutorials/how-to-install-r-on-ubuntu-18-04-quickstart

I keep getting an error during installation:

sudo Rscript CAMPP.R
....

Loading required package: Matrix
Loaded glmnet 4.0
**Error in FUN(X[[i]], ...) : there is no package called ‘sva’**
Además: There were 50 or more warnings (use warnings() to see the first 50)
**Error: Ups! Something went wrong, one or more R-package dependencies are not installed correctly. Check the script CAMPPmissingpackages.R. Alternatively you can download and use the Packrat library freeze, see manual for specifics. Packrat library in brief:**

 (1.) Download the Packrat library from the CAMPP repository on github (if you have not already), and make sure it is located in the same folder as CAMPP.R.

 (2.) set the flat -e to TRUE, and run the pipeline.
Ejecución interrumpida



Can you help me please.
Best

**Comment by ThildeBT** [comment]
Hi @jorge-h2020,
I have looked at it and updated my R-version to 4.0, so we are running from the same starting point. I suggest you try the non-renv way. I will look at what the renv error one of the coming days.
So for now here is what you do:
1. Download both the CAMPP.R and CAMPPFunctions.R script **again** and place them in your folder.
2. Run the pipeline and do **not** set the packrat flag, just leave it out.
You will likely get an error message at the end, but that is due to some dependencies which might be old, and this is not so problematic. So try running the pipeline again right away regardless of any error message thrown. 
3. Run the pipeline **again**

Let me know how it goes,

Cheers

Thilde

**Comment by ThildeBT** [comment]
Hi @jorge-h2020,
I have reconstructed the renv.lock file, so you can try and replace it with the old one and run the _-e stable_ way again, **if** the other way does not work :)

Thanks a lot with the debugging help, it is super useful to me 👍 

Cheers,

Thilde

**Comment by jorge-h2020** [comment]
Hi @ThildeBT,

Now with the new upgrade and R version 4 in ubuntu, it's working for me. Thank you very much for your help.

Cheers
Jorge

**Comment by ThildeBT** [comment]
Hi @jorge-h2020,
You are very welcome :) I will close this thread, but please free to open a new one for other issues.

Cheers,

Thilde
